### ISSUE TITLE
脚本中的安装nconvert的代码的问题

### ISSUE THREAD

**Issue by ylxb2016** [Aniverse/bluray#2]
https://github.com/Aniverse/bluray/blob/4ac8d35adcaeb93bfccdd8705024572fbc7888d9/bluray#L149

大神，这个是否应该修改为
`wget --no-check-certificate -qO /usr/local/bin/nconvert https://raw.githubusercontent.com/Aniverse/bluray/master/tools/nconvert && chmod 755 /usr/local/bin/vcs ; `

**Comment by Aniverse** [comment]
是的……这个问题之前我发现了，也改了，但一直没推送到 GitHub（其实改了但都还没提交 commit）

Edited：刚改了
