### ISSUE TITLE
求问星大，这个bluray脚本我安装了完全没问题是怎么回事。。。

### ISSUE THREAD

**Issue by Yirenxs** [Aniverse/bluray#3]
我在OP, C2350那台机子上用xshell, root权限运行 
wget -qO /usr/local/bin/bluray https://github.com/Aniverse/bluray/raw/master/bluray
没任何反映

运行
cd ; git clone https://github.com/Aniverse/bluray ; chmod -R +x $HOME/bluray
显示
Cloning into 'bluray'...
remote: Enumerating objects: 74, done.
remote: Counting objects: 100% (74/74), done.
remote: Compressing objects: 100% (51/51), done.
remote: Total 379 (delta 42), reused 53 (delta 23), pack-reused 305
Receiving objects: 100% (379/379), 109.95 MiB | 10.43 MiB/s, done.
Resolving deltas: 100% (171/171), done.
Checking connectivity... done.
这是安装成功了吧。

然后我不管运行
chmod +x /usr/local/bin/bluray
还是
echo "PATH=$HOME/bluray:$PATH" >> $HOME/.bashrc ; PATH=$HOME/bluray:$PATH
都没任何反映，，，

不知道该如何使用bluray这个脚本，能否麻烦星大回复，感谢。

**Comment by Aniverse** [comment]
这个是安装步骤不是使用步骤，使用的话输入 `bluray` 即可

**Comment by Yirenxs** [comment]
晕倒，原来是这样，，，多谢星大指导。
